version: '3.8'

services:
  healthai-api:
    build: .
    container_name: healthai_microservice
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - PYTHONUNBUFFERED=1
    restart: always
